// cryptos.js

export const cryptos = [
    'bitcoin',
    'ethereum',
    'binancecoin',
    'cardano',
    'solana',
    'ripple',
    'polkadot',
    'dogecoin',
    'litecoin',
    'chainlink',
    'uniswap',
    'stellar',
    'usd-coin',
    'dogecoin',
    'avalanche-2',
    'shiba-inu',
    'cosmos',
    'tron',
    'monero',
    'ethereum-classic',
    'algorand',
    'vechain',
    'filecoin',
    'axie-infinity',
    'zilliqa',
    'harmony',
    'hedera',
    'decentraland',
    'the-sandbox',
    'terra-luna',
    'lido',
    'near-protocol',
    'optimism',
    'aave',
    'compound-coin',
    'dai',
    'maker',
    'thorchain',
    'elrond',
    'chiliz',
    'sushi',
    'safemoon',
    'pancakeswap',
    'avax',
    'arbitrum',
    'fantom',
    'flow',
    'polygon',
    'steem',
    'nexo',
    'kusama',
    'xrp',
    'custom-coin', // Criptomoeda personalizada
  ];
  